### ISSUE TITLE
Загрузка карт из нескольких подразделов базы?

### ISSUE THREAD

**Issue by SherAlex1998** [HidasMato/role_cards_spells#1]
Есть возможность сделать загрузка карт из нескольких разделов в базе (например - отобразить сразу заклинания чародея и паладина) без надобности редактирования поля csv?-

**Comment by HidasMato** [comment]
Это действие можно выполнить при помощи пары кликов и копипасты
Не вижу смысла добавления такого функционала
Он будет только перегружать интерфейс

Тем более, когда отображается большое количество карточек на странице, конструктор крашится при попытке сделать подгонку описания
